//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SappySharp.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SappySharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sappy.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All supported pictures.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;File.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playlist.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too cool!.
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;USPLZ&gt;.
        /// </summary>
        internal static string _10000 {
            get {
                return ResourceManager.GetString("10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sappy 2006\n----------\nBy Kyoufu Kawa\n\nBased on the original player\nby Andrew Lim (DJ Bouche)\n\nContains portions of the following\ntools previously written by Kawa:\n\ Maple (sound dumper and songtable scanner)\n\ Juicer (track dumper/inserter)\n\nThis product includes software\ndeveloped by vbAccelerator.\n\n\nThanks and greetings to:\n\ Drag     \n\ Tony     \n\ Rick     \n\ Matt     \n\ Prime    \n\ Someguy  \n\ Jeff     \n\ Sakaki   \n\ Hapi-san \n\ Shii     \n\ Kotoko   \n\ Coke Lite\nand Mr. McM [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please load a game....
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Looking for song list....
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song #$INDEX.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song #$INDEX - $NAME.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No playlists.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No songs.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Open.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The auto-detector does not work on &quot;Golden Sun&quot; games.\n\nThese include:\n&quot;Golden Sun&quot;\n&quot;Golden Sun - The Lost Age&quot;\n&quot;Mario Golf Advance Tour&quot;\n\nSorry for the inconveniance..
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loaded from seperate XML file..
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Exit.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GBA Roms (*.gba).
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Tasks.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Tracks.
        /// </summary>
        internal static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the tracks you want to import:.
        /// </summary>
        internal static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select where you want to save the tracks:.
        /// </summary>
        internal static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Header.
        /// </summary>
        internal static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First track.
        /// </summary>
        internal static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track offsets.
        /// </summary>
        internal static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The second track will be saved right after the first track. Headers are copied..
        /// </summary>
        internal static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must select at least one track..
        /// </summary>
        internal static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a starting track offset..
        /// </summary>
        internal static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a header offset..
        /// </summary>
        internal static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing to import tracks....
        /// </summary>
        internal static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Importing $FILE to $TO....
        /// </summary>
        internal static string _2011 {
            get {
                return ResourceManager.GetString("2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving header....
        /// </summary>
        internal static string _2012 {
            get {
                return ResourceManager.GetString("2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done. Do you want to set the proper entry in the Song Table?.
        /// </summary>
        internal static string _2013 {
            get {
                return ResourceManager.GetString("2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voicegroup.
        /// </summary>
        internal static string _2016 {
            get {
                return ResourceManager.GetString("2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot find $XML. Create a new, blank version now?.
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The game you loaded (gamecode $CODE) is not known.\n\nWould you like to scan for the song table now?.
        /// </summary>
        internal static string _205 {
            get {
                return ResourceManager.GetString("205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t find the song table. This game probably doesn&apos;t use M4A at all, or at least a different version..
        /// </summary>
        internal static string _206 {
            get {
                return ResourceManager.GetString("206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found the song table at 0x$TBL. Saving bare bones entry to XML file for quick reloading....
        /// </summary>
        internal static string _207 {
            get {
                return ResourceManager.GetString("207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in the XML file!\n\n$ERROR\n$CAUSE\n\nPlease correct this error and try again..
        /// </summary>
        internal static string _208 {
            get {
                return ResourceManager.GetString("208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid gamecode - it&apos;s all zeroes!.
        /// </summary>
        internal static string _209 {
            get {
                return ResourceManager.GetString("209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter game&apos;s name:.
        /// </summary>
        internal static string _210 {
            get {
                return ResourceManager.GetString("210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter creator&apos;s name:.
        /// </summary>
        internal static string _211 {
            get {
                return ResourceManager.GetString("211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter tagger&apos;s name:.
        /// </summary>
        internal static string _212 {
            get {
                return ResourceManager.GetString("212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Options.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Tracks.
        /// </summary>
        internal static string _3000 {
            get {
                return ResourceManager.GetString("3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the tracks you want to export:.
        /// </summary>
        internal static string _3001 {
            get {
                return ResourceManager.GetString("3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select where you want to save the tracks:.
        /// </summary>
        internal static string _3002 {
            get {
                return ResourceManager.GetString("3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tags.
        /// </summary>
        internal static string _3003 {
            get {
                return ResourceManager.GetString("3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any instance of $T is replaced by the current track&apos;s number. Likewise, $P is replaced by the track&apos;s base pointer..
        /// </summary>
        internal static string _3004 {
            get {
                return ResourceManager.GetString("3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must select at least one track..
        /// </summary>
        internal static string _3005 {
            get {
                return ResourceManager.GetString("3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter a file name pattern..
        /// </summary>
        internal static string _3006 {
            get {
                return ResourceManager.GetString("3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing to dump tracks....
        /// </summary>
        internal static string _3007 {
            get {
                return ResourceManager.GetString("3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dumping track $TRACK....
        /// </summary>
        internal static string _3008 {
            get {
                return ResourceManager.GetString("3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dumping to $FILE....
        /// </summary>
        internal static string _3009 {
            get {
                return ResourceManager.GetString("3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skipping track $TRACK..
        /// </summary>
        internal static string _3010 {
            get {
                return ResourceManager.GetString("3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a full file pattern..
        /// </summary>
        internal static string _3011 {
            get {
                return ResourceManager.GetString("3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use &amp;MIDI driver.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use &amp;Wave driver.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Gameboy Mode.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Settings.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Import LST file.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seek by &amp;Playlist.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select MIDI device....
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remap MIDI instruments....
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Help.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assemble .S file.
        /// </summary>
        internal static string _4000 {
            get {
                return ResourceManager.GetString("4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .S file name.
        /// </summary>
        internal static string _4001 {
            get {
                return ResourceManager.GetString("4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base destination offset.
        /// </summary>
        internal static string _4002 {
            get {
                return ResourceManager.GetString("4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voicegroup offset.
        /// </summary>
        internal static string _4003 {
            get {
                return ResourceManager.GetString("4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assemble that ugly thing!.
        /// </summary>
        internal static string _4004 {
            get {
                return ResourceManager.GetString("4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a base offset..
        /// </summary>
        internal static string _4005 {
            get {
                return ResourceManager.GetString("4005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a voicegroup offset..
        /// </summary>
        internal static string _4006 {
            get {
                return ResourceManager.GetString("4006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a file name..
        /// </summary>
        internal static string _4007 {
            get {
                return ResourceManager.GetString("4007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;About.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;The Helmeted Rodent on-line.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contents.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tasks.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIDI Mapper.
        /// </summary>
        internal static string _5000 {
            get {
                return ResourceManager.GetString("5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instruments.
        /// </summary>
        internal static string _5001 {
            get {
                return ResourceManager.GetString("5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drums.
        /// </summary>
        internal static string _5002 {
            get {
                return ResourceManager.GetString("5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remap to.
        /// </summary>
        internal static string _5003 {
            get {
                return ResourceManager.GetString("5003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instrument.
        /// </summary>
        internal static string _5004 {
            get {
                return ResourceManager.GetString("5004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drum Key.
        /// </summary>
        internal static string _5005 {
            get {
                return ResourceManager.GetString("5005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transpose.
        /// </summary>
        internal static string _5006 {
            get {
                return ResourceManager.GetString("5006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listen.
        /// </summary>
        internal static string _5007 {
            get {
                return ResourceManager.GetString("5007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string _5008 {
            get {
                return ResourceManager.GetString("5008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record to MIDI.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export tracks.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import tracks.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export samples.
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assemble song.
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string _6000 {
            get {
                return ResourceManager.GetString("6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ROM database.
        /// </summary>
        internal static string _6001 {
            get {
                return ResourceManager.GetString("6001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Song repeats.
        /// </summary>
        internal static string _6002 {
            get {
                return ResourceManager.GetString("6002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (0 for infinite).
        /// </summary>
        internal static string _6003 {
            get {
                return ResourceManager.GetString("6003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload last ROM on startup.
        /// </summary>
        internal static string _6004 {
            get {
                return ResourceManager.GetString("6004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now Playing.
        /// </summary>
        internal static string _6005 {
            get {
                return ResourceManager.GetString("6005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write Now Playing info for mIRC script.
        /// </summary>
        internal static string _6006 {
            get {
                return ResourceManager.GetString("6006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send Now Playing info to MSN Messenger.
        /// </summary>
        internal static string _6007 {
            get {
                return ResourceManager.GetString("6007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface.
        /// </summary>
        internal static string _6008 {
            get {
                return ResourceManager.GetString("6008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable annoying sounds.
        /// </summary>
        internal static string _6009 {
            get {
                return ResourceManager.GetString("6009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force nice task bar.
        /// </summary>
        internal static string _6010 {
            get {
                return ResourceManager.GetString("6010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playback.
        /// </summary>
        internal static string _6011 {
            get {
                return ResourceManager.GetString("6011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skin.
        /// </summary>
        internal static string _6012 {
            get {
                return ResourceManager.GetString("6012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hue.
        /// </summary>
        internal static string _6013 {
            get {
                return ResourceManager.GetString("6013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturation.
        /// </summary>
        internal static string _6014 {
            get {
                return ResourceManager.GetString("6014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide task bar (classic mode).
        /// </summary>
        internal static string _6015 {
            get {
                return ResourceManager.GetString("6015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown game.
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown code.
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown creator.
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown tagger.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Made by.
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tagged by.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Songtable:.
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done!.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opens a ROM for playback..
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export samples.
        /// </summary>
        internal static string _7000 {
            get {
                return ResourceManager.GetString("7000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as.
        /// </summary>
        internal static string _7001 {
            get {
                return ResourceManager.GetString("7001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name pattern.
        /// </summary>
        internal static string _7002 {
            get {
                return ResourceManager.GetString("7002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File formats.
        /// </summary>
        internal static string _7003 {
            get {
                return ResourceManager.GetString("7003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name patterns.
        /// </summary>
        internal static string _7004 {
            get {
                return ResourceManager.GetString("7004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any instance of $I is replaced by the instruments voice number. Likewise, $P is replaced by the instrument&apos;s pointer..
        /// </summary>
        internal static string _7005 {
            get {
                return ResourceManager.GetString("7005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw wave files (*.raw).
        /// </summary>
        internal static string _7010 {
            get {
                return ResourceManager.GetString("7010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows wave files (*.wav).
        /// </summary>
        internal static string _7011 {
            get {
                return ResourceManager.GetString("7011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ImpulseTracker samples (*.its).
        /// </summary>
        internal static string _7012 {
            get {
                return ResourceManager.GetString("7012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sappy source files (*.s).
        /// </summary>
        internal static string _7013 {
            get {
                return ResourceManager.GetString("7013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RAW files contain raw, unprocessed PCM sound data and nothing else. Not even a header. They cannot loop..
        /// </summary>
        internal static string _7020 {
            get {
                return ResourceManager.GetString("7020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WAV files are like RAW, but have headers and can be played as-is without tools. They cannot loop..
        /// </summary>
        internal static string _7021 {
            get {
                return ResourceManager.GetString("7021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ITS files can be used in ModPlug Tracker and retain the sample&apos;s original loop point..
        /// </summary>
        internal static string _7022 {
            get {
                return ResourceManager.GetString("7022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sappy source files are what the Sappy toolkit uses. They are in ARM Assembly, but contain no actual code at all, only data and directives..
        /// </summary>
        internal static string _7023 {
            get {
                return ResourceManager.GetString("7023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #MAPLE EXPORTED SAMPLE - PLEASE CHECK THE HEADER VALUES!.
        /// </summary>
        internal static string _7030 {
            get {
                return ResourceManager.GetString("7030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exits the program..
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play music with the old MIDI driver..
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play music with the new Wave driver..
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play all music with square waves..
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About the program..
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visit our website!.
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save this song as a standard MIDI file..
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyzing song....
        /// </summary>
        internal static string _8000 {
            get {
                return ResourceManager.GetString("8000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filling sample pool....
        /// </summary>
        internal static string _8001 {
            get {
                return ResourceManager.GetString("8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finishing....
        /// </summary>
        internal static string _8002 {
            get {
                return ResourceManager.GetString("8002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export one or more tracks in this song to files..
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace one or more tracks in this song with tracks saved to file..
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export all sounds in this song to files..
        /// </summary>
        internal static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assemble MID2AGB output to binary..
        /// </summary>
        internal static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select MIDI device.
        /// </summary>
        internal static string _9000 {
            get {
                return ResourceManager.GetString("9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hardware port.
        /// </summary>
        internal static string _9001 {
            get {
                return ResourceManager.GetString("9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synthesizer.
        /// </summary>
        internal static string _9002 {
            get {
                return ResourceManager.GetString("9002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Squarewave Synth.
        /// </summary>
        internal static string _9003 {
            get {
                return ResourceManager.GetString("9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FM Synth.
        /// </summary>
        internal static string _9004 {
            get {
                return ResourceManager.GetString("9004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MS Midi Mapper.
        /// </summary>
        internal static string _9005 {
            get {
                return ResourceManager.GetString("9005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HW Wavetable Synth.
        /// </summary>
        internal static string _9006 {
            get {
                return ResourceManager.GetString("9006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software Synth.
        /// </summary>
        internal static string _9007 {
            get {
                return ResourceManager.GetString("9007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Header.
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voices.
        /// </summary>
        internal static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        internal static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon APP {
            get {
                object obj = ResourceManager.GetObject("APP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BANNER {
            get {
                object obj = ResourceManager.GetObject("BANNER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BARSAMPLES {
            get {
                object obj = ResourceManager.GetObject("BARSAMPLES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon BETA {
            get {
                object obj = ResourceManager.GetObject("BETA", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon CLASSICSAPPY {
            get {
                object obj = ResourceManager.GetObject("CLASSICSAPPY", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CREDITSFONT {
            get {
                object obj = ResourceManager.GetObject("CREDITSFONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CREDITSLOGOS {
            get {
                object obj = ResourceManager.GetObject("CREDITSLOGOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon GLIDER {
            get {
                object obj = ResourceManager.GetObject("GLIDER", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NOPIC {
            get {
                object obj = ResourceManager.GetObject("NOPIC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Skin100 {
            get {
                object obj = ResourceManager.GetObject("Skin100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Skin101 {
            get {
                object obj = ResourceManager.GetObject("Skin101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Skin102 {
            get {
                object obj = ResourceManager.GetObject("Skin102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STATUSICONS {
            get {
                object obj = ResourceManager.GetObject("STATUSICONS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLICONS {
            get {
                object obj = ResourceManager.GetObject("TOOLICONS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon TWOKAYFIVE {
            get {
                object obj = ResourceManager.GetObject("TWOKAYFIVE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
