name: .NET Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_NAME: SappySharp
  UNIT_TEST: false

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      #run: dotnet build --configuration Release --no-restore --property:OutputPath=..\release
      run: dotnet msbuild -p:Configuration=Release -p:OutputPath=..\release
    - name: Unit tests
      if: ${{ env.UNIT_TEST }}
      run: dotnet test --no-restore --verbosity normal
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SOLUTION_NAME }}
        path: release\
